name: Docker Image CI

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: |
          repigeons/masteredis:${{ steps.get_tag.outputs.TAG }}
          repigeons/masteredis:latest
        platforms: linux/amd64,linux/arm64/v8
        push: true
